### ISSUE TITLE
Staging - After sending /no to coming with a bike. The user is unlisted as a biker.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#10]
**Repro steps**
1) /biker
2) /yes
3) /no
4) /yes

**Expected Result**
Entry for that day is updated to Yes

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/76416344-2fb9ae00-639b-11ea-94c8-26f8a1b4ed0e.png)

**System Info**

**Comment by jasperSchreel** [comment]
set_biker() sneaked into the bike_today function 
Has been fixed now
