### ISSUE TITLE
/session on negative time displays the wrong time.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#12]
**Repro steps**
1) Start new session ( 3 minute long so far )
2) Take a break that's longer than the session has been active ( 10 minutes )
3) /session

**Expected Result**
Active session on timby for 0 hours and -7 minutes

**Actual Result**
Active session on timby for 0 hours and 53 minutes

**System Info**

**Comment by ken-de-moor** [comment]
Info: the negative time is displayed correctly in the frontend overview, just not in the /session

**Comment by jasperSchreel** [comment]
implementation for negative session times has been implemented for /session
