### ISSUE TITLE
Staging - Time is lost when switching projects.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#13]
**Repro steps**
1) Do the request, set session to timby, do the request again one minute later
2) Wait 3 minutes.
3) Change Project => /project ifan
4) Do the request again one minute later.

**Expected Result**
4 minutes on timby ( 1 + 3 )
1 minute on ifan

**Actual Result**
The 3 minutes are lost
![image](https://user-images.githubusercontent.com/59569757/76431263-a19cf200-63b1-11ea-8507-2623f4ea6ce2.png)

**System Info**

**Comment by jasperSchreel** [comment]
Fixed
Updates current session before switching project
