### ISSUE TITLE
Staging - Your session has been closed is sent once for each project switch.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#14]
**Repro steps**
1) Switch project a couple of times
2) Send requests in between each switch
3) Wait 5 minutes for session to close

**Expected Result**
"Your session has been closed"

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/76437678-34418f00-63ba-11ea-86aa-05c7821009ba.png)

**System Info**

**Comment by jasperSchreel** [comment]
fixed: only 1 msg send when session ends to each active user
