### ISSUE TITLE
Staging - Your session has been closed message is no longer sent.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#15]
**Repro steps**
1) Start a session on any project for any duration
2) Let it expire by not refreshing for 5 minutes

**Expected Result**
"Your session has been closed"

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/76620186-e4cfa000-652c-11ea-8131-db9a0681afad.png)

**System Info**

**Comment by jasperSchreel** [comment]
Cron job wasn't setup on staging server yet.
Added now
