### ISSUE TITLE
Staging - User is never asked if they came by bike.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#16]
**Repro steps**
1) List yourself as a biker
2) Start you first session that day

**Expected Result**
"Did you come by bike today? Please reply using /yes or /no"

**Actual Result**
Even after user is listed with /biker, the question is never asked
However it is possible to add yourself as biker by doing /yes independently of being asked or not.

**System Info**

**Comment by jasperSchreel** [comment]
crontab job wasn't installed on staging server yet
