### ISSUE TITLE
when asked for a project, you should be given some options based on popularity and your history

### ISSUE THREAD

**Issue by JonasWijne** [jimbertools/timby#18]
In these flows

- [ ] When doing /p

- [ ] When doing /project

- [x] When a session without project is started and timby asks project

In the telegram API there is an option to give inline keyboards this would be useful if you would get some buttons based on your history

---

https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/91164889-1b126d80-e6d0-11ea-84dd-79e0843e1fe3.png)

Works on initial project asking, but not on /p or /project

**Comment by lennertdefauw** [comment]
Employees said to show the buttons at /p or /project was not necessary, only when you have no project selected
