### ISSUE TITLE
on the timby frontend all unique views should have a unique route 

### ISSUE THREAD

**Issue by JonasWijne** [jimbertools/timby#20]
ex. http://192.168.2.10/personal/jonaswijne instead of http://192.168.2.10/personal/ with jonaswijne in memory 

This will facilitate the setting of personal bookmarks

**Comment by ken-de-moor** [comment]
Some are still missing.

**Dashboard**
User Time By Week
Workday Planned Times

**Personal**
General overview
Week calendar
Year overview

**Projects**
Selected project

**Comment by ken-de-moor** [comment]
Go to personal select a user, and calendar => https://nginx_timby.jack.jimber.org/personal/azertyalex/calendar

Refresh this => Select box is now empty

----------------------------

Go to projects from this view => Goes to link https://nginx_timby.jack.jimber.org/projects/3BotConnect/calendar but the project view does not even have a calendar.

Also when refreshing the select box is empty
