### ISSUE TITLE
on the timby frontend there should be a day calender to see when my session was

### ISSUE THREAD

**Issue by JonasWijne** [jimbertools/timby#24]
- [x] Day should start on monday, not on sunday
- [x] It should be possible to see other weeks than current week
- [x] Don't show sessions less than 2 minutes long. ( unreadable clutter )
- [x] Start the calendar hours on the earliest worked hours instead of midnight
- [x] Holidays should be listed as "Holiday"
- [x] Add 24 hours view instead of 12

ex. 
![image](https://user-images.githubusercontent.com/6184820/86215354-c7c2e980-bb7c-11ea-896a-9a66c0d51954.png)

**Comment by ken-de-moor** [comment]
Use the existing vue component for this, don't customly create a calendar

https://vuetifyjs.com/en/components/calendars/
