### ISSUE TITLE
Session keeps going after close

### ISSUE THREAD

**Issue by GillesMommerency** [jimbertools/timby#35]
When force closing (http://localhost:8080/api/forceclose/gillesmommerency)
The session time is not stopped and keeps going up.

![image](https://user-images.githubusercontent.com/43674162/89889480-f5ff0480-dbd1-11ea-91cf-72713988cb07.png)

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/91191198-c59c8780-e6f4-11ea-963f-63b852dea2ff.png)

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/92089306-454de480-edce-11ea-99b8-35e519279940.png)
