### ISSUE TITLE
When working with no active session, project 'None' is inserted into the database

### ISSUE THREAD

**Issue by lennertdefauw** [jimbertools/timby#36]
![image](https://user-images.githubusercontent.com/43674202/89981435-2ac39800-dc74-11ea-978a-f487787e12d2.png)

![image](https://user-images.githubusercontent.com/43674202/89981496-42028580-dc74-11ea-97db-32989abbb839.png)

**Comment by ken-de-moor** [comment]
As designed, should not be changed, it's possible to work without selecting a project.
