### ISSUE TITLE
User time by week should be the default view instead of workday planned times

### ISSUE THREAD

**Issue by lennertdefauw** [jimbertools/timby#49]
The 2 tabs on the Dashboard page should be switched

**Comment by ken-de-moor** [comment]
Getting workday planned times as default still

**Comment by ken-de-moor** [comment]
It seems these tabs got swapped around by this fix?

![image](https://user-images.githubusercontent.com/59569757/91163346-bb1ac780-e6cd-11ea-8960-c4b3d8e80684.png)
