### ISSUE TITLE
/help should have /break, and should remove /start

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#5]
All commonly used commands should be included in the /help command.

This means the following should be added, and future added commansd should also be added.
/break

The following should be removed
/start

**Comment by jasperSchreel** [comment]
![image](https://user-images.githubusercontent.com/17983141/75893900-bd454d00-5e33-11ea-8c7d-0cb8ec2c76c3.png)

on branch fix/v1.2.0
