### ISSUE TITLE
Change display of  user time by week tab

### ISSUE THREAD

**Issue by lennertdefauw** [jimbertools/timby#51]
Instead of using expansion panels on user time by week, use expandable rows

documentation: https://vuetifyjs.com/en/components/data-tables/#expandable-rows

**Comment by ken-de-moor** [comment]
Should also expand/collapse when clicking the entire bar, not only the icon on the left.

![image](https://user-images.githubusercontent.com/59569757/91163683-4431fe80-e6ce-11ea-89ab-46711d0c9ad3.png)
