### ISSUE TITLE
Staging - After adding a manual entry, a new session is started for the currently active session project.

### ISSUE THREAD

**Issue by ken-de-moor** [jimbertools/timby#9]
**Repro steps**
1) Start a session
2) Add a manual entry

**Expected Result**
The session is still continued, it shouldn't be interrupted to add a manual.

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/76414606-f2075600-6397-11ea-8f76-f11057791842.png)

**System Info**

**Comment by jasperSchreel** [comment]
Manual session types are no longer considered valid 'last session' types

![image](https://user-images.githubusercontent.com/17983141/76419402-8bd30100-63a0-11ea-82eb-dd524bb336f2.png)
